name: Release on Maven

on:
  workflow_call: { }

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'

      - name: Give permissions to Gradle
        run: chmod +x gradlew

      - name: Release
        run: ./gradlew publishAndReleaseToMavenCentral
